version: '3.8'
services:
  web:
    image: node:latest
    ports:
      - "80:80"
    volumes:
      - .:/usr/app/
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  default:
    external:
      name: my-network
      